### ISSUE TITLE
Close uARM after KERNEL PANIC

### ISSUE THREAD

**Issue by MartelliEnrico** [mellotanica/uARM#1]
Is it possible to add the ability to close uARM (with a non zero exit code) when called with the flags -e and -x, after getting a PANIC call? This would improve automatic testing with uARM.

**Comment by mellotanica** [comment]
it is possible but not easy and conceptually incorrect, let me explain.. the PANIC instruction is entirely provided by the BIOS code, it has nothing to do with the emulated hardware, this means that tracking the PANIC call in hardware would be feasible in two ways:
- adding a hardware PANIC instruction
- waiting for the PC to get to the PANIC BIOS function address.

the first case is conceptually correct, but it would require a hardware refactoring, the second case is conceptually wrong because the hardware should not have dependencies on the software.

a quick solution is to only use HALT instead of PANIC instructions and rely only on terminal/printer output to determine if something bad happened

**Comment by MartelliEnrico** [comment]
Thanks for the reply.
